### ISSUE TITLE
Questions about the paper

### ISSUE THREAD

**Issue by hanzhiwangchn** [Codsir/pad_bias_correction#1]
Hi,

I’ve read your recent paper about the age-level bias correction in Brain age Prediction and found it relatively straightforward and robust. It gives me some more insights into this predictive bias. However, I have a simple question about this bias correction approach.

My question is will this age-level bias correction approach affect the model performance (MAE) further, since the MAE will typically increase using cole's approach. Have you observed such an increase in MAE and how does it compared with cole's method?

Many thanks,
Hanzhi

**Comment by saulgoodenough** [comment]
Hi Hanzhi, 

Thanks for your question. The age prediction accuracy change after age-level bias correction is still not tested. When we considered the correction of PAD bias, we aimed to acquire a clinically reasonable phenotype via the transformation of PAD. Due to the uncertainty such as measurement error and noise, it seems that the accuracy is forced to increase in spending of increment of bias. Thus, the accuracy may decrease because of the decrease of bias. In another aspect, the accuracy may increase since the age-level correction uses the chronological age. 

After all, in my view, it is still meaningful to further test the prediction accuracy after correction, and I would like to give you some results later.

**Comment by hanzhiwangchn** [comment]
Yes, definitely. The more important thing should be an unbiased estimator of the brain age although a more accurate estimate is also desired. Thanks for the explanation☺️
